Repository ToDoTurtle/ToDoTurtle, pull requests merged in 2023-02, with the labels that each got.

#28 feat-ktlint
  .github/hooks/pre-commit
  CONTRIBUTING.md
Labels: documentation, enhancement

#36 fix: create hook directory if it doesn't exist
  CONTRIBUTING.md
Labels: bug

#26 feat: add update reminder use case #5
  .idea/codeStyles/Project.xml
  src/main/kotlin/note/application/NoteUpdater.kt
  src/main/kotlin/note/domain/Note.kt
  src/main/kotlin/note/domain/NotePrimitives.kt
  src/main/kotlin/note/domain/exceptions/UnchangedNoteException.kt
  src/test/kotlin/note/application/NoteUpdaterTest.kt
  src/test/kotlin/note/mothers/DescriptionMother.kt
  src/test/kotlin/note/mothers/NoteMother.kt
  src/test/kotlin/note/mothers/TitleMother.kt
Labels: feature

#37 feat: create device use case
  src/main/kotlin/device/application/CreateDevice.kt
  src/main/kotlin/device/domain/Device.kt
  src/main/kotlin/device/domain/DeviceIdentifier.kt
  src/main/kotlin/device/domain/DeviceName.kt
  src/main/kotlin/device/domain/DeviceRepository.kt
  src/main/kotlin/device/domain/exceptions/AlreadyExistingDevice.kt
  src/main/kotlin/device/domain/exceptions/IllegalDeviceNameException.kt
  src/main/kotlin/device/domain/exceptions/InvalidUUIDException.kt
  src/test/kotlin/device/application/CreateDeviceTest.kt
  src/test/kotlin/device/mothers/DeviceIdentifierMother.kt
  src/test/kotlin/device/mothers/DeviceMother.kt
  src/test/kotlin/device/mothers/DeviceNameMother.kt
Labels: feature

#38 feat: get notification
  src/main/kotlin/notification/application/NotificationGetter.kt
  src/main/kotlin/notification/domain/Notification.kt
  src/main/kotlin/notification/domain/NotificationRepository.kt
  src/main/kotlin/shared/domain/Identifier.kt
  src/main/kotlin/shared/domain/IdentifierGenerator.kt
  src/main/kotlin/shared/domain/exceptions/InvalidUUIDException.kt
  src/test/kotlin/note/application/NoteDeleterTest.kt
  src/test/kotlin/note/application/NoteSearcherTest.kt
  src/test/kotlin/note/application/NoteUpdaterTest.kt
  src/test/kotlin/note/mothers/NoteIdentifierMother.kt
  src/test/kotlin/note/mothers/NoteMother.kt
  src/test/kotlin/notification/application/NotificationGetterTest.kt
  src/test/kotlin/notification/mothers/NotificationMother.kt
  src/test/kotlin/shared/mothers/IdentifierMother.kt
Labels: feature
