Repository ToDoTurtle/ToDoTurtle, pull requests merged in 2023-03, with the labels that each got.

#46 feat: refactor note to follow primitive and language standards
  src/main/kotlin/note/application/NoteChanger.kt
  src/main/kotlin/note/application/NoteCreator.kt
  src/main/kotlin/note/application/NoteRemover.kt
  src/main/kotlin/note/application/NoteSearcher.kt
  src/main/kotlin/note/domain/NoteRepository.kt
  src/test/kotlin/note/application/NoteDeleterTest.kt
  src/test/kotlin/note/application/NoteSaverTest.kt
  src/test/kotlin/note/application/NoteUpdaterTest.kt
Labels: feature

#54 doc: add invalid identifier exception
  src/main/kotlin/device/application/DeviceSearcher.kt
  src/main/kotlin/note/application/NoteRemover.kt
  src/main/kotlin/note/application/NoteSearcher.kt
Labels: documentation

#50 feat(get-notifications): add use case implementation
  src/main/kotlin/notification/application/NotificationGetter.kt
  src/main/kotlin/notification/application/NotificationSearcher.kt
  src/main/kotlin/notification/domain/Notification.kt
  src/main/kotlin/notification/domain/NotificationRepository.kt
  src/test/kotlin/notification/application/NotificationGetterTest.kt
  src/test/kotlin/notification/mothers/NotificationMother.kt
Labels: feature

#56 refactor(notifications): use domain language
  src/test/kotlin/notification/application/NotificationSearcherTest.kt
Labels: refactor

#51 feat: delete device
  src/main/kotlin/device/application/DeviceRemover.kt
  src/main/kotlin/device/application/DeviceSearcher.kt
  src/main/kotlin/device/domain/DeviceRepository.kt
  src/main/kotlin/device/domain/exceptions/NonExistentDeviceException.kt
  src/test/kotlin/device/application/DeviceRemoverTest.kt
  src/test/kotlin/device/application/DeviceSearcherTest.kt
  src/test/kotlin/note/application/NoteDeleterTest.kt
Labels: feature

#55 feat: notification creation
  src/main/kotlin/notification/application/NotificationCreator.kt
  src/main/kotlin/notification/application/NotificationPrimitives.kt
  src/main/kotlin/notification/domain/Notification.kt
  src/main/kotlin/notification/domain/NotificationRepository.kt
  src/main/kotlin/notification/domain/exceptions/AlreadyConfiguredNotification.kt
  src/test/kotlin/deadline/mothers/TimeMother.kt
  src/test/kotlin/note/mothers/NoteMother.kt
  src/test/kotlin/notification/application/NotificationCreatorTest.kt
  src/test/kotlin/notification/mothers/NotificationMother.kt
Labels: feature

#57 feat: update device
  src/main/kotlin/device/application/DeviceChanger.kt
  src/main/kotlin/device/application/DeviceCreator.kt
  src/main/kotlin/device/application/DeviceRemover.kt
  src/main/kotlin/device/domain/DeviceIdentifier.kt
  src/main/kotlin/device/domain/DevicePrimitives.kt
  src/main/kotlin/device/domain/exceptions/InvalidUUIDException.kt
  src/main/kotlin/device/domain/exceptions/UnchangedDeviceException.kt
  src/main/kotlin/note/domain/NoteIdentifier.kt
  src/test/kotlin/device/application/DeviceCreatorTest.kt
  src/test/kotlin/device/application/DeviceSearcherTest.kt
  src/test/kotlin/device/application/DeviceUpdaterTest.kt
  src/test/kotlin/device/mothers/DeviceIdentifierMother.kt
  src/test/kotlin/device/mothers/DeviceMother.kt
  src/test/kotlin/device/mothers/DeviceNameMother.kt
Labels: feature

#58 refactor(note): add domain language
  src/test/kotlin/note/application/NoteRemoverTest.kt
Labels: refactor
